// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1C6P6IODpiL3ceylVAFinv5itTsFKZU',
    appId: '1:318146529129:web:71811b23d35cfb00bfdff8',
    messagingSenderId: '318146529129',
    projectId: 'chat-app-9f97f',
    authDomain: 'chat-app-9f97f.firebaseapp.com',
    storageBucket: 'chat-app-9f97f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3kG7k07CMf8jQIdrp0KMG6jqa3DlnkA',
    appId: '1:318146529129:android:08198ffac1bd53a5bfdff8',
    messagingSenderId: '318146529129',
    projectId: 'chat-app-9f97f',
    storageBucket: 'chat-app-9f97f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUH96l77AUe-LNNpX05X-ICRHRF5kOow',
    appId: '1:318146529129:ios:96522465338d30b7bfdff8',
    messagingSenderId: '318146529129',
    projectId: 'chat-app-9f97f',
    storageBucket: 'chat-app-9f97f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUH96l77AUe-LNNpX05X-ICRHRF5kOow',
    appId: '1:318146529129:ios:12be6b813e6c19e7bfdff8',
    messagingSenderId: '318146529129',
    projectId: 'chat-app-9f97f',
    storageBucket: 'chat-app-9f97f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
